### PR TITLE
Get the list of servers from whatsmydns api endpoint

### PR DESCRIPTION
**Pull request by t0mer**
Whatsmydns ha an api endpoint to get the updated list of servers.
I changed the crapper file to support and get the list from that API.
The servers list will be written to a text file named "servers.txt" and then you can copy it to "servers.py".

### CODE REVIEW

**Comment by chelnak** [comment]
Hey this is cool!

I wonder, now that this endpoint is available, could we call it directly and remove the scraping script?

Thank you for your contribution!

**Comment by t0mer** [comment]
> Hey this is cool!
> 
> I wonder, now that this endpoint is available, could we call it directly and remove the scraping script?
> 
> Thank you for your contribution!

We can do that, but i noticed that the list changes from time to time.
For example, I ran the scrapper from different locations (IPs) and I got two different lists.

I'll combine the lists and push ane version.

**Comment by chelnak** [comment]
Interesting thank you 🙏 

I'm happy to merge this today!

In the future, would you be interested in working on a PR that integrates your API call in to the application itself?

**Comment by t0mer** [comment]
> Interesting thank you 🙏
> 
> I'm happy to merge this today!
> 
> In the future, would you be interested in working on a PR that integrates your API call in to the application itself?

I have another idea.
I will create a small web service that scrapp the list of servers using multiple ip's and in your code we eill get the list from my service.
Already started working on it (:

**Comment by t0mer** [comment]
You can access the following address to get the servers list:
https://wmd.techblog.co.il/servers

**Pull request merged**
